#!/bin/bash
# Install RStudio
apt-get install -y r-base
apt-get install -y r-base-dev
R -e "install.packages(c('shiny', 'ggplot2', 'dplyr', 'tidyverse'), repos='http://cran.rstudio.com/')"

#for install seurat in install.R
# Install system dependencies for Seurat
apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev
