#!/bin/bash
# Install RStudio
apt-get install -y r-base
apt-get install -y r-base-dev
R -e "install.packages(c('shiny', 'ggplot2', 'dplyr', 'tidyverse'), repos='http://cran.rstudio.com/')"
R -e "source('install_seurat.R')"
