name: mybinder
channels:
  - defaults
  - conda-forge
  - bioconda  # if using bio-related packages
dependencies:
  # R dependencies
  - r-base=4.4.1
  - r-essentials
  - r-ggplot2
  - r-seurat
  - r-studio-2024.04.0  # Optional: if you can specify a version
  
  # Python dependencies
  - python=3.11
  - ipykernel
  - jupyter
  - traitlets=5.9.0
  - pip  # Add pip here
  
  # If you need pip-installed dependencies
  - pip:
      - numpy
      - pandas
      - seaborn
